[build]
  # The command Netlify runs to build your Vite project
  command = "npm run build"
  
  # The directory Vite outputs your production-ready files into
  publish = "dist"

[[redirects]]
  from = "/tpcl"
  to = "https://docs.google.com/spreadsheets/d/137Jqpwop9ueLpzEnMtZ41OkYh9Pr3PgVx_o29GJx4QY/"
  status = 301