[build]
  # The command Netlify runs to build your Vite project
  command = "npm run build"
  
  # The directory Vite outputs your production-ready files into
  publish = "dist"

[[redirects]]
  from = "/tpcl"
  to = "/tpcl/"
  status = 301